const tabs=document.querySelectorAll('.auth-tabs button');
tabs.forEach(tab=>tab.onclick=()=>{tabs.forEach(x=>x.classList.toggle('active',x===tab));document.querySelectorAll('.auth-panel').forEach(x=>x.hidden=x.id!==tab.dataset.tab);});
const clickSound=()=>{try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(420,c.currentTime);o.frequency.exponentialRampToValueAtTime(720,c.currentTime+.08);g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.1);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.11);}catch{}};
document.addEventListener('click',e=>{if(e.target.closest('button,a'))clickSound();});
async function request(form,url){const status=form.querySelector('.form-status');status.textContent='Подождите…';try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ошибка сервера.');return d;}catch(e){status.textContent=e.message||'Ошибка сервера.';return null;}}
document.querySelector('[data-api]').onsubmit=async e=>{e.preventDefault();const d=await request(e.currentTarget,e.currentTarget.dataset.api);if(d?.ok)showCabinet(d.nickname);};
document.querySelector('#start-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=await request(f,'/api/auth-start');if(d?.ok){document.querySelector('#verify-form').hidden=false;document.querySelector('#verify-form [name=nickname]').value=f.nickname.value;f.hidden=true;}};
document.querySelector('#verify-form').onsubmit=async e=>{e.preventDefault();const d=await request(e.currentTarget,'/api/auth-verify');if(d?.ok)e.currentTarget.innerHTML='<p class="form-status">Аккаунт создан. Теперь можно войти.</p>';};
async function showCabinet(nickname){document.querySelector('.auth-tabs').hidden=true;document.querySelectorAll('.auth-panel').forEach(x=>x.hidden=true);if(document.querySelector('.cabinet'))return;const box=document.createElement('section');box.className='cabinet';box.innerHTML=`<p class="eyebrow">BOLTOVKA ANARCHY</p><div class="cabinet-head"><img class="skin-head" src="https://mc-heads.net/avatar/${encodeURIComponent(nickname)}/160" alt="Голова ${nickname}"><div><p class="cabinet-label">ЛИЧНЫЙ КАБИНЕТ</p><h2>${nickname}</h2><span class="cabinet-status">Данные сервера загружаются…</span></div></div><div class="cabinet-grid"><article><span>ПРИВИЛЕГИЯ</span><b data-profile="privilege">—</b></article><article><span>ДОНАТ-ВАЛЮТА</span><b data-profile="donate">—</b></article><article><span>ИГРОВАЯ ВАЛЮТА</span><b data-profile="balance">—</b></article><article><span>ОТЫГРАНО</span><b data-profile="playtime">—</b></article></div><p class="cabinet-note">Вход сохранён на 30 дней на этом устройстве. Данные обновляются при синхронизации с сервером.</p><button class="button secondary" id="logout">Выйти</button>`;document.querySelector('.account-page').append(box);document.querySelector('#logout').onclick=async()=>{await fetch('/api/auth-logout',{method:'POST'});location.reload();};try{const r=await fetch('/api/profile?nickname='+encodeURIComponent(nickname)),d=await r.json();if(!r.ok)throw new Error();const p=d.profile;box.querySelector('[data-profile="privilege"]').textContent=p.privilege;box.querySelector('[data-profile="donate"]').textContent=p.donate_balance;box.querySelector('[data-profile="balance"]').textContent=p.balance;box.querySelector('[data-profile="playtime"]').textContent=p.playtime;box.querySelector('.cabinet-status').textContent='Профиль синхронизирован с сервером';}catch{box.querySelector('.cabinet-status').textContent='Сервер пока не передал игровые данные';}}
fetch('/api/auth-session').then(r=>r.ok?r.json():null).then(d=>d?.nickname&&showCabinet(d.nickname)).catch(()=>{});
